"""
Mr.Holmes — catálogo de serviços externos OSINT, separados por categoria.
Cada serviço fica apenas na categoria correspondente.
"""

EXTERNAL_SERVICES = {
    "pessoas": {
        "label": "Pessoas & Username",
        "icon": "🧠",
        "description": "Perfis públicos, handles e busca por nome",
        "page_keys": ["pessoas", "email", "osint"],
        "services": [
            {
                "id": "mind",
                "name": "Mind Search",
                "url": "https://mind-7.org/?r=fala_melo",
                "icon": "🧠",
                "description": "Busca avançada de informações pessoais",
                "use_for": "Nome, documento, perfil",
                "source": "web",
            },
            {
                "id": "sherlock",
                "name": "Sherlock",
                "url": "https://github.com/sherlock-project/sherlock",
                "icon": "🕵️",
                "description": "Username em centenas de redes sociais",
                "use_for": "Handle / username",
                "source": "github",
            },
            {
                "id": "maigret",
                "name": "Maigret",
                "url": "https://github.com/soxoj/maigret",
                "icon": "📰",
                "description": "Coleta perfis e report completo por username",
                "use_for": "Username → relatório",
                "source": "github",
            },
            {
                "id": "socialscan",
                "name": "SocialScan",
                "url": "https://github.com/iojw/socialscan",
                "icon": "👥",
                "description": "Checa username ou email em plataformas",
                "use_for": "Username ou email",
                "source": "github",
            },
            {
                "id": "whatsmyname",
                "name": "WhatsMyName Web",
                "url": "https://whatsmyname.app/",
                "icon": "🏷️",
                "description": "Busca de username em sites (web UI)",
                "use_for": "Handle em múltiplos sites",
                "source": "web",
            },
            {
                "id": "epieos",
                "name": "Epieos",
                "url": "https://epieos.com/",
                "icon": "🔍",
                "description": "Lookup de email e telefone em fontes abertas",
                "use_for": "Email / telefone",
                "source": "web",
            },
            {
                "id": "namechk",
                "name": "Namechk",
                "url": "https://namechk.com/",
                "icon": "✅",
                "description": "Disponibilidade de username em redes",
                "use_for": "Checar handle",
                "source": "web",
            },
            {
                "id": "osintframework",
                "name": "OSINT Framework",
                "url": "https://osintframework.com/",
                "icon": "🗺️",
                "description": "Mapa indexado de fontes OSINT",
                "use_for": "Descobrir fontes por tipo",
                "source": "web",
            },
        ],
    },
    "telefone": {
        "label": "Telefone",
        "icon": "📱",
        "description": "Caller-ID, reputação e footprint de números",
        "page_keys": ["telefone"],
        "services": [
            {
                "id": "syncme",
                "name": "Sync.me",
                "url": "https://sync.me/pt-br/",
                "icon": "📱",
                "description": "Agenda reversa e identificação de contato",
                "use_for": "Caller ID / WhatsApp",
                "source": "web",
            },
            {
                "id": "phoneinfoga",
                "name": "PhoneInfoga",
                "url": "https://github.com/sundowndev/phoneinfoga",
                "icon": "📞",
                "description": "Framework OSINT #1 para números (17k+ ★)",
                "use_for": "Número internacional / footprint",
                "source": "github",
            },
            {
                "id": "ignorant",
                "name": "Ignorant",
                "url": "https://github.com/megadose/ignorant",
                "icon": "🔕",
                "description": "Número em Instagram, Snapchat etc.",
                "use_for": "Número → contas sociais",
                "source": "github",
            },
            {
                "id": "phunter",
                "name": "Phunter",
                "url": "https://github.com/N0rz3/Phunter",
                "icon": "🔎",
                "description": "Coleta multiponto a partir de um telefone",
                "use_for": "Recon por número",
                "source": "github",
            },
            {
                "id": "searchphone",
                "name": "SearchPhone",
                "url": "https://github.com/HackUnderway/SearchPhone",
                "icon": "🛰️",
                "description": "Toolkit multi-API (Google, Numverify, Reddit…)",
                "use_for": "Busca ampla + relatório",
                "source": "github",
            },
            {
                "id": "moriarty",
                "name": "Moriarty Project",
                "url": "https://github.com/AzizKpln/Moriarty-Project",
                "icon": "🧩",
                "description": "Footprints a partir do número informado",
                "use_for": "Perfil básico do número",
                "source": "github",
            },
            {
                "id": "telephone-osint",
                "name": "Telephone-OSINT Toolbox",
                "url": "https://github.com/The-Osint-Toolbox/Telephone-OSINT",
                "icon": "🧰",
                "description": "Coleção curada de tools de phone lookup",
                "use_for": "Referência de fontes",
                "source": "github",
            },
            {
                "id": "phonebook-cz",
                "name": "Phonebook.cz",
                "url": "https://phonebook.cz/",
                "icon": "📒",
                "description": "Busca em dumps públicos indexados",
                "use_for": "Número / email em dumps",
                "source": "web",
            },
            {
                "id": "truecaller",
                "name": "Truecaller",
                "url": "https://www.truecaller.com/",
                "icon": "✅",
                "description": "Caller ID colaborativo (conta)",
                "use_for": "Nome associado ao número",
                "source": "web",
            },
            {
                "id": "freelookup",
                "name": "Free-Lookup",
                "url": "https://free-lookup.net/",
                "icon": "🌐",
                "description": "Lookup web gratuito de números",
                "use_for": "Consulta rápida",
                "source": "web",
            },
            {
                "id": "spamcalls",
                "name": "SpamCalls",
                "url": "https://spamcalls.net/",
                "icon": "🚫",
                "description": "Reputação de spam / denúncias",
                "use_for": "Número suspeito",
                "source": "web",
            },
            {
                "id": "whosenumber",
                "name": "WhoseNumber",
                "url": "https://whosenumber.info/",
                "icon": "❓",
                "description": "Comentários e reputação de números",
                "use_for": "Quem ligou / reclamações",
                "source": "web",
            },
            {
                "id": "callapp",
                "name": "CallApp",
                "url": "https://callapp.com/",
                "icon": "📲",
                "description": "Caller ID e bloqueio de spam",
                "use_for": "Identificação de contato",
                "source": "web",
            },
            {
                "id": "eyecon",
                "name": "Eyecon",
                "url": "https://www.eyecon-app.com/",
                "icon": "👁️",
                "description": "Caller ID com foto (app)",
                "use_for": "Foto/nome associado",
                "source": "web",
            },
            {
                "id": "getcontact",
                "name": "GetContact",
                "url": "https://www.getcontact.com/",
                "icon": "📇",
                "description": "Tags e nomes salvos por outros usuários",
                "use_for": "Como o número aparece na agenda",
                "source": "web",
            },
            {
                "id": "spydialer",
                "name": "SpyDialer",
                "url": "https://www.spydialer.com/",
                "icon": "🎙️",
                "description": "Reverse lookup e voicemail (US-focused)",
                "use_for": "Número EUA / voicemail",
                "source": "web",
            },
            {
                "id": "numlookup",
                "name": "NumLookup",
                "url": "https://www.numlookup.com/",
                "icon": "🔢",
                "description": "Reverse phone lookup online",
                "use_for": "Consulta rápida de número",
                "source": "web",
            },
        ],
    },
    "email": {
        "label": "Email",
        "icon": "✉️",
        "description": "Validação, presença e vazamentos por email",
        "page_keys": ["email"],
        "services": [
            {
                "id": "holehe",
                "name": "Holehe",
                "url": "https://github.com/megadose/holehe",
                "icon": "🕳️",
                "description": "Em quais sites o email está cadastrado",
                "use_for": "Email → contas",
                "source": "github",
            },
            {
                "id": "hunter",
                "name": "Hunter.io",
                "url": "https://hunter.io/",
                "icon": "🏹",
                "description": "Encontra emails profissionais por domínio",
                "use_for": "Domínio → emails",
                "source": "web",
            },
            {
                "id": "emailrep",
                "name": "Emailrep",
                "url": "https://emailrep.io/",
                "icon": "📊",
                "description": "Reputação e sinais de risco do email",
                "use_for": "Email suspeito",
                "source": "web",
            },
            {
                "id": "epieos-mail",
                "name": "Epieos (email)",
                "url": "https://epieos.com/",
                "icon": "🔍",
                "description": "Lookup OSINT de endereço de email",
                "use_for": "Email em fontes abertas",
                "source": "web",
            },
            {
                "id": "mxtoolbox",
                "name": "MxToolbox",
                "url": "https://mxtoolbox.com/",
                "icon": "📬",
                "description": "MX, blacklist e saúde de domínio de email",
                "use_for": "Domínio de email",
                "source": "web",
            },
        ],
    },
    "leaks": {
        "label": "Leaks",
        "icon": "🔓",
        "description": "Breaches, dumps e hashes (fontes públicas/com conta)",
        "page_keys": ["leaks", "email"],
        "services": [
            {
                "id": "dehashed",
                "name": "Dehashed",
                "url": "https://www.dehashed.com/",
                "icon": "🔓",
                "description": "Busca em dumps e violações",
                "use_for": "Email, username, domínio",
                "source": "web",
            },
            {
                "id": "hibp",
                "name": "Have I Been Pwned",
                "url": "https://haveibeenpwned.com/",
                "icon": "📧",
                "description": "Breaches públicos por email",
                "use_for": "Email comprometido",
                "source": "web",
            },
            {
                "id": "intelx",
                "name": "Intelligence X",
                "url": "https://intelx.io/",
                "icon": "🗄️",
                "description": "Search engine de leaks e arquivos públicos",
                "use_for": "Email, domínio, seletores",
                "source": "web",
            },
            {
                "id": "leakcheck",
                "name": "LeakCheck",
                "url": "https://leakcheck.io/",
                "icon": "🛡️",
                "description": "Checagem de credenciais vazadas",
                "use_for": "Email / username",
                "source": "web",
            },
            {
                "id": "hudsonrock",
                "name": "Hudson Rock",
                "url": "https://www.hudsonrock.com/free-tools",
                "icon": "🪨",
                "description": "Ferramentas gratuitas ligadas a stealer logs",
                "use_for": "Email / domínio (free tools)",
                "source": "web",
            },
            {
                "id": "psbdmp",
                "name": "PSBDMP",
                "url": "https://psbdmp.ws/",
                "icon": "📝",
                "description": "Busca em pastes públicos",
                "use_for": "Email / string em pastes",
                "source": "web",
            },
            {
                "id": "crackstation",
                "name": "CrackStation",
                "url": "https://crackstation.net/",
                "icon": "🔑",
                "description": "Lookup de hashes (forense)",
                "use_for": "Hash MD5/SHA",
                "source": "web",
            },
        ],
    },
    "dominio": {
        "label": "Domínio & Web",
        "icon": "🕸️",
        "description": "DNS, WHOIS, certificados e fingerprint de site",
        "page_keys": ["dominio", "rede"],
        "services": [
            {
                "id": "webcheck",
                "name": "Web-Check",
                "url": "https://web-check.xyz/",
                "icon": "🕸️",
                "description": "SSL, DNS, headers e fingerprint",
                "use_for": "Domínio / URL",
                "source": "web",
            },
            {
                "id": "crtsh",
                "name": "crt.sh",
                "url": "https://crt.sh/",
                "icon": "📜",
                "description": "Certificate Transparency logs",
                "use_for": "Subdomínios via CT",
                "source": "web",
            },
            {
                "id": "securitytrails",
                "name": "SecurityTrails",
                "url": "https://securitytrails.com/",
                "icon": "🛤️",
                "description": "Histórico DNS e inventário de domínio",
                "use_for": "Domínio / subdomínios",
                "source": "web",
            },
            {
                "id": "dnsdumpster",
                "name": "DNSDumpster",
                "url": "https://dnsdumpster.com/",
                "icon": "💣",
                "description": "Mapa DNS e hosts descobertos",
                "use_for": "Recon de domínio",
                "source": "web",
            },
            {
                "id": "shodan",
                "name": "Shodan",
                "url": "https://www.shodan.io/",
                "icon": "🛰️",
                "description": "Dispositivos e serviços expostos",
                "use_for": "IP / banner / porta",
                "source": "web",
            },
            {
                "id": "censys",
                "name": "Censys",
                "url": "https://search.censys.io/",
                "icon": "🔭",
                "description": "Hosts e certificados na internet",
                "use_for": "IP / domínio / cert",
                "source": "web",
            },
            {
                "id": "urlscan",
                "name": "urlscan.io",
                "url": "https://urlscan.io/",
                "icon": "🧪",
                "description": "Sandbox de URL",
                "use_for": "URL suspeita",
                "source": "web",
            },
            {
                "id": "viewdns",
                "name": "ViewDNS",
                "url": "https://viewdns.info/",
                "icon": "🔎",
                "description": "WHOIS, reverse IP, DNS history",
                "use_for": "Domínio e IP",
                "source": "web",
            },
            {
                "id": "virustotal",
                "name": "VirusTotal",
                "url": "https://www.virustotal.com/",
                "icon": "🦠",
                "description": "Reputação de URL, arquivo e domínio",
                "use_for": "URL / hash / domínio",
                "source": "web",
            },
            {
                "id": "ssllabs",
                "name": "SSL Labs",
                "url": "https://www.ssllabs.com/ssltest/",
                "icon": "🔒",
                "description": "Teste profundo de configuração TLS",
                "use_for": "HTTPS do domínio",
                "source": "web",
            },
            {
                "id": "securityheaders",
                "name": "SecurityHeaders",
                "url": "https://securityheaders.com/",
                "icon": "🧱",
                "description": "Nota dos headers de segurança HTTP",
                "use_for": "URL / domínio",
                "source": "web",
            },
            {
                "id": "builtwith",
                "name": "BuiltWith",
                "url": "https://builtwith.com/",
                "icon": "🏗️",
                "description": "Stack tecnológica do site",
                "use_for": "Tecnologias do domínio",
                "source": "web",
            },
        ],
    },
    "imagem": {
        "label": "Imagem",
        "icon": "🖼️",
        "description": "EXIF, reverse image e forense leve",
        "page_keys": ["imagem", "osint"],
        "services": [
            {
                "id": "jimpl",
                "name": "Jimpl",
                "url": "https://jimpl.com/",
                "icon": "🖼️",
                "description": "EXIF/metadados de fotos",
                "use_for": "JPEG/PNG",
                "source": "web",
            },
            {
                "id": "tineye",
                "name": "TinEye",
                "url": "https://tineye.com/",
                "icon": "👁️",
                "description": "Busca reversa de imagem",
                "use_for": "Onde a foto aparece",
                "source": "web",
            },
            {
                "id": "yandex-images",
                "name": "Yandex Images",
                "url": "https://yandex.com/images/",
                "icon": "🟡",
                "description": "Reverse image forte em faces/cenas",
                "use_for": "Foto de pessoa/local",
                "source": "web",
            },
            {
                "id": "google-lens",
                "name": "Google Lens",
                "url": "https://lens.google.com/",
                "icon": "📷",
                "description": "Identificação visual e reverse image",
                "use_for": "Objetos, texto, lugares",
                "source": "web",
            },
            {
                "id": "invid",
                "name": "InVID Verification",
                "url": "https://www.invid-project.eu/tools-and-services/invid-verification-plugin/",
                "icon": "🎬",
                "description": "Verificação de imagens e vídeos",
                "use_for": "Desinformação / mídia",
                "source": "web",
            },
            {
                "id": "fotoforensics",
                "name": "FotoForensics",
                "url": "https://fotoforensics.com/",
                "icon": "🧬",
                "description": "Análise ELA de manipulação",
                "use_for": "Foto possivelmente editada",
                "source": "web",
            },
            {
                "id": "aperisolve",
                "name": "Aperi'Solve",
                "url": "https://www.aperisolve.com/",
                "icon": "🧩",
                "description": "Stego + metadados no browser",
                "use_for": "Dados ocultos em imagem",
                "source": "web",
            },
            {
                "id": "stegonline",
                "name": "StegOnline",
                "url": "https://georgeom.net/StegOnline/upload",
                "icon": "🔬",
                "description": "Explorador LSB",
                "use_for": "Canais de cor / bits",
                "source": "web",
            },
            {
                "id": "exiftool",
                "name": "ExifTool",
                "url": "https://exiftool.org/",
                "icon": "📋",
                "description": "Padrão de metadados imagem/doc",
                "use_for": "EXIF, IPTC, XMP",
                "source": "web",
            },
        ],
    },
    "utilitarios": {
        "label": "Utilitários",
        "icon": "🧰",
        "description": "Decoders, arquivos e referência rápida",
        "page_keys": ["osint", "utilitarios"],
        "services": [
            {
                "id": "cyberchef",
                "name": "CyberChef",
                "url": "https://gchq.github.io/CyberChef/",
                "icon": "🍳",
                "description": "Encode/decode e transformações",
                "use_for": "Base64, hex, JWT",
                "source": "web",
            },
            {
                "id": "wayback",
                "name": "Wayback Machine",
                "url": "https://web.archive.org/",
                "icon": "⏪",
                "description": "Histórico de páginas web",
                "use_for": "URL antiga / snapshot",
                "source": "web",
            },
            {
                "id": "archive-today",
                "name": "archive.today",
                "url": "https://archive.ph/",
                "icon": "📌",
                "description": "Snapshot on-demand de páginas",
                "use_for": "Preservar URL",
                "source": "web",
            },
            {
                "id": "ipinfo",
                "name": "IPinfo",
                "url": "https://ipinfo.io/",
                "icon": "🌍",
                "description": "Geo e ASN de endereços IP",
                "use_for": "IP lookup",
                "source": "web",
            },
            {
                "id": "wigle",
                "name": "WiGLE",
                "url": "https://wigle.net/",
                "icon": "📡",
                "description": "Mapa de redes Wi‑Fi",
                "use_for": "SSID / BSSID",
                "source": "web",
            },
            {
                "id": "toolsley",
                "name": "Toolsley",
                "url": "https://www.toolsley.com/",
                "icon": "🛠️",
                "description": "Utilitários forenses online",
                "use_for": "Tipo de arquivo / strings",
                "source": "web",
            },
            {
                "id": "hackingtool",
                "name": "hackingtool (ref.)",
                "url": "https://github.com/Z4nzu/hackingtool",
                "icon": "📦",
                "description": "Catálogo amplo — só referência OSINT",
                "use_for": "Descobrir tools de recon",
                "source": "github",
            },
        ],
    },
    "darkweb": {
        "label": "Dark web (oficial)",
        "icon": "🕵️",
        "description": "Projetos oficiais de briefing .onion — rodam fora do Holmes",
        "page_keys": ["osint", "leaks", "premium"],
        "services": [
            {
                "id": "robin",
                "name": "Robin",
                "url": "https://github.com/apurvsinghgautam/robin",
                "icon": "🕵️",
                "description": "OSINT de dark web com LLM: query, filtro, scrape e relatório",
                "use_for": "Ferramenta embutida em OSINT Premium",
                "source": "github",
            },
            {
                "id": "robin-tools-list",
                "name": "Dark Web OSINT Tools",
                "url": "https://github.com/apurvsinghgautam/dark-web-osint-tools",
                "icon": "🗂️",
                "description": "Lista curada pelo autor do Robin (referência, não é o Holmes)",
                "use_for": "Descobrir fontes oficiais",
                "source": "github",
            },
            {
                "id": "ahmia",
                "name": "Ahmia",
                "url": "https://ahmia.fi/",
                "icon": "🧅",
                "description": "Busca pública de sites .onion (clearnet)",
                "use_for": "Pesquisa educacional indexada",
                "source": "web",
            },
        ],
    },
    "recon_cli": {
        "label": "Recon CLI",
        "icon": "⚙️",
        "description": "Tools de terminal (links oficiais — não instala no site)",
        "page_keys": ["dominio", "osint", "rede"],
        "services": [
            {
                "id": "subfinder",
                "name": "Subfinder",
                "url": "https://github.com/projectdiscovery/subfinder",
                "icon": "🌐",
                "description": "Enum passiva de subdomínios",
                "use_for": "Subdomínios",
                "source": "github",
            },
            {
                "id": "httpx",
                "name": "httpx",
                "url": "https://github.com/projectdiscovery/httpx",
                "icon": "📡",
                "description": "Probe HTTP rápido",
                "use_for": "Hosts vivos",
                "source": "github",
            },
            {
                "id": "dnsx",
                "name": "dnsx",
                "url": "https://github.com/projectdiscovery/dnsx",
                "icon": "🧭",
                "description": "Toolkit DNS",
                "use_for": "Resolução DNS",
                "source": "github",
            },
            {
                "id": "theharvester",
                "name": "theHarvester",
                "url": "https://github.com/laramies/theHarvester",
                "icon": "🌾",
                "description": "Emails e hosts em fontes abertas",
                "use_for": "Email / domínio",
                "source": "github",
            },
            {
                "id": "amass",
                "name": "OWASP Amass",
                "url": "https://github.com/owasp-amass/amass",
                "icon": "🗺️",
                "description": "Mapeamento de superfície de ativos",
                "use_for": "Assets de domínio",
                "source": "github",
            },
            {
                "id": "gitleaks",
                "name": "Gitleaks",
                "url": "https://github.com/gitleaks/gitleaks",
                "icon": "🔐",
                "description": "Secrets em repositórios Git",
                "use_for": "Repo autorizado",
                "source": "github",
            },
            {
                "id": "trufflehog",
                "name": "TruffleHog",
                "url": "https://github.com/trufflesecurity/trufflehog",
                "icon": "🐷",
                "description": "API keys em código",
                "use_for": "Credenciais em git",
                "source": "github",
            },
            {
                "id": "photon",
                "name": "Photon",
                "url": "https://github.com/s0md3v/Photon",
                "icon": "⚡",
                "description": "Crawler OSINT de sites",
                "use_for": "Mapear URLs / emails em site",
                "source": "github",
            },
        ],
    },
}


def get_categories():
    return list(EXTERNAL_SERVICES.keys())


def get_category(category_key):
    return EXTERNAL_SERVICES.get(category_key)


def get_all_categories():
    return EXTERNAL_SERVICES


def get_services_for_page(page_key):
    key = (page_key or "").strip().lower()
    blocks = []
    for cat_key, cat in EXTERNAL_SERVICES.items():
        if key in [k.lower() for k in cat.get("page_keys", [])] or key == cat_key:
            blocks.append((cat_key, cat))
    return blocks


def get_all_services_flat():
    out = []
    for cat_key, cat in EXTERNAL_SERVICES.items():
        for svc in cat.get("services", []):
            item = dict(svc)
            item["category_key"] = cat_key
            item["category_label"] = cat["label"]
            item["category_icon"] = cat["icon"]
            out.append(item)
    return out
